"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import Basics from "@/components/Basics";
const BASES=[2,6,8,10,16]; const NAMES={easy:"ง่าย",medium:"ปานกลาง",hard:"ยาก"} as const; type Level=keyof typeof NAMES; type Tab="home"|"basics"|"learn"|"practice"|"exam"|"calculator"|"score";
type Q={decimal:number;from:number;to:number;shown:string;answer:string}; type Record={name?:string;date:string;level:Level;correct:number;total:number};
const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)]; const makeQ=(level:Level):Q=>{const max={easy:31,medium:255,hard:4095}[level],decimal=1+Math.floor(Math.random()*max);let from=pick(BASES),to=pick(BASES);while(to===from)to=pick(BASES);return{decimal,from,to,shown:decimal.toString(from).toUpperCase(),answer:decimal.toString(to).toUpperCase()}};
export default function BaseLabApp({initialTab="home"}:{initialTab?:Tab}){const router=useRouter();const[tab]=useState<Tab>(initialTab);const[records,setRecords]=useState<Record[]>([]);const paths={home:"/",basics:"/basics",learn:"/learn",practice:"/practice",exam:"/exam",calculator:"/calculator",score:"/score"} as const;const go=(next:Tab)=>router.push(paths[next]);useEffect(()=>setRecords(JSON.parse(localStorage.getItem("baselabExamHistory")||"[]")),[]);const save=(r:Omit<Record,"name">)=>{const name=window.prompt("กรอกชื่อ–นามสกุลผู้ทำข้อสอบ")?.trim();if(!name)return;const next=[{...r,name},...records].slice(0,50);setRecords(next);localStorage.setItem("baselabExamHistory",JSON.stringify(next))};const remove=(i:number)=>{if(!confirm("ลบคะแนนรายการนี้ใช่หรือไม่?"))return;const next=records.filter((_,index)=>index!==i);setRecords(next);localStorage.setItem("baselabExamHistory",JSON.stringify(next))};return <div><Header tab={tab} setTab={go}/>{tab==="home"&&<Home go={go}/>} {tab==="basics"&&<Basics go={go}/>} {tab==="learn"&&<Learn go={go}/>} {tab==="practice"&&<Practice go={go}/>} {tab==="exam"&&<Exam go={go} save={save}/>} {tab==="calculator"&&<Calculator/>} {tab==="score"&&<Score records={records} remove={remove} clear={()=>{setRecords([]);localStorage.removeItem("baselabExamHistory")}} go={go}/>}<footer className="flex justify-between bg-[#071c36] px-[8vw] py-8 text-white"><b className="text-[#1dd1c1]">BASELAB BY JEEP</b><div className="text-right text-sm"><b>นางสาวทิฆัมพร มีหิรัญ</b><small className="block text-slate-400">056860405627-1</small></div></footer></div>}
function Header({tab,setTab}:{tab:Tab,setTab:(t:Tab)=>void}){const items:[Tab,string][]=[["home","หน้าแรก"],["basics","พื้นฐาน"],["learn","การแปลง"],["practice","ฝึก"],["exam","โจทย์จริง"],["calculator","คำนวณ"],["score","คะแนน"]];return <header className="sticky top-0 z-30 flex min-h-16 items-center gap-8 bg-[#071c36] px-[5vw] text-white"><button onClick={()=>setTab("home")} className="mono font-black text-[#1dd1c1]"><span className="mr-2 rounded border-2 border-[#1dd1c1] p-2">BLJ</span><span className="hidden sm:inline">BASELAB BY JEEP</span></button><nav className="flex flex-1 gap-1 overflow-x-auto">{items.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap px-3 py-5 text-sm ${tab===id?"border-b-4 border-[#1dd1c1] text-white":"text-slate-400"}`}>{label}</button>)}</nav><span className="hidden text-right text-xs text-slate-300 lg:block">นางสาวทิฆัมพร มีหิรัญ</span></header>}
const Hero=({tag,title,sub}:{tag:string,title:string,sub:string})=><section className="bg-[#071c36] px-[8vw] py-16 text-white"><p className="mono text-xs tracking-[.25em] text-[#1dd1c1]">{tag}</p><h1 className="mt-4 text-4xl font-black md:text-6xl">{title}</h1><p className="mt-4 text-slate-400">{sub}</p></section>;
function Home({go}:{go:(t:Tab)=>void}){const steps:[Tab,string,string][]=[["basics","01 เรียนพื้นฐาน","รู้จักตัวเลขแต่ละฐาน"],["learn","02 เรียนวิธีแปลง","ครบทุกคู่ฐาน"],["practice","03 โจทย์ฝึก","เฉลยทันที"],["exam","04 โจทย์จริง","สุ่ม 10 ข้อ"],["calculator","05 คำนวณ","ตรวจค่าอัตโนมัติ"],["score","06 คะแนน","ดูประวัติ"]];return <><Hero tag="BASE 2 • 6 • 8 • 10 • 16" title="เรียนเลขฐาน จากเข้าใจไปใช้จริง" sub="เริ่มจากพื้นฐาน แล้วเรียนการแปลง ฝึกโจทย์ ทำข้อสอบ และดูคะแนน"/><main className="mx-auto -mt-7 mb-20 grid max-w-6xl gap-3 px-5 sm:grid-cols-2 lg:grid-cols-6">{steps.map(([id,a,b])=><button onClick={()=>go(id)} key={id} className="glass rounded-xl bg-white p-6 text-left hover:-translate-y-1"><b className="text-[#008f86]">{a}</b><small className="mt-3 block text-slate-500">{b}</small></button>)}</main></>}
function Learn({go}:{go:(t:Tab)=>void}){
  const[from,setFrom]=useState(2),[to,setTo]=useState(6);
  const value=from===2?45:from===6?95:from===8?83:from===10?156:175;
  const shown=value.toString(from).toUpperCase(),result=value.toString(to).toUpperCase();
  const expansion=shown.split("").map((c,i)=>{const digit=parseInt(c,36),power=shown.length-1-i,label=digit>9?`${c}(${digit})`:c;return `${label} × ${from}^${power}`}).join(" + ");
  const divisions=useMemo(()=>{let n=value,a:string[]=[];while(n>0){a.push(`${n} ÷ ${to} = ${Math.floor(n/to)} เศษ ${n%to}`);n=Math.floor(n/to)}return a},[value,to]);
  const chooseRoute=(a:number,b:number)=>{setFrom(a);setTo(b)};
  return <><Hero tag="20 CONVERSION LESSONS" title="เรียนวิธีแปลงทีละคู่ฐาน" sub="เลือกฐานต้นทางและฐานปลายทาง แล้วเรียนจากโจทย์ตัวอย่างพร้อมวิธีทำทีละขั้น"/><main className="glass mx-auto -mt-8 mb-20 max-w-5xl rounded-xl bg-white p-6 md:p-10">
    <section className="mb-7 rounded-xl border border-[#a9ddd6] bg-[#e9f8f5] p-5"><h2 className="text-xl font-black">ทำไมต้องผ่านฐาน 10 ก่อน?</h2><p className="mt-2 text-sm leading-6 text-slate-600"><b>ไม่ใช่ว่าฐาน {from} แปลงเป็นฐาน {to} โดยตรงไม่ได้</b> แต่การสร้างกฎเทียบแต่ละคู่จะจำยาก เราจึงใช้ฐาน 10 เป็น “ภาษากลาง” เพื่อหาค่าจริงก่อน แล้วเขียนค่านั้นใหม่ในฐานปลายทาง ค่าเดิมไม่เปลี่ยน มีเพียงรูปแบบการเขียนที่เปลี่ยนไป</p><div className="mt-4 flex flex-wrap items-center gap-2 font-mono font-bold"><span className="rounded bg-[#071c36] px-3 py-2 text-white">{shown}<sub>{from}</sub></span><span className="text-[#247b73]">→ หาค่าจริง →</span><span className="rounded bg-[#071c36] px-3 py-2 text-white">{value}<sub>10</sub></span><span className="text-[#247b73]">→ เขียนใหม่ →</span><span className="rounded bg-[#071c36] px-3 py-2 text-white">{result}<sub>{to}</sub></span></div></section>
    <BasePicker label="1. เลือก ‘แปลงจาก’ ฐาน" value={from} set={b=>{setFrom(b);if(b===to)setTo(BASES.find(x=>x!==b)!)}}/><BasePicker label="2. เลือก ‘แปลงเป็น’ ฐาน" value={to} set={setTo} disabled={from}/>
    <article className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-6"><p className="mono text-xs tracking-wider text-[#008f86]">แปลงจากฐาน {from} → เป็นฐาน {to}</p><h2 className="mt-2 text-2xl font-black">โจทย์: จงแปลง {shown}<sub>{from}</sub> ให้เป็นเลขฐาน {to}</h2><div className="mt-5 rounded-xl bg-[#071c36] p-5 text-white"><span className="text-xs font-bold text-[#1dd1c1]">โจทย์ตัวอย่าง</span><p className="mono mt-2 text-2xl font-black">{shown}<sub>{from}</sub> → ?<sub>{to}</sub></p><p className="mt-2 text-sm text-slate-400">ทำตามขั้นที่ 1 และขั้นที่ 2 ด้านล่าง แล้วจึงดูคำตอบ</p></div>
      <div className="mt-5 grid gap-4 md:grid-cols-2"><section className="rounded-xl bg-white p-5 shadow-sm"><span className="rounded-full bg-[#1dd1c1] px-3 py-1 text-xs font-black">ขั้นที่ 1</span><h3 className="mt-4 text-lg font-black">แปลงจากฐาน {from} เป็นฐาน 10</h3>{from===10?<p className="mt-3 leading-7 text-slate-600">{shown} เป็นฐาน 10 อยู่แล้ว จึงได้ <b>{value}<sub>10</sub></b></p>:<><p className="mt-3 text-sm text-slate-500">กระจายค่าประจำหลักของ {shown}<sub>{from}</sub></p><p className="mono mt-3 break-words rounded-lg bg-slate-100 p-3 text-sm leading-7">{expansion}<br/>= <b>{value}<sub>10</sub></b></p></>}</section>
      <section className="rounded-xl bg-[#071c36] p-5 text-white"><span className="rounded-full bg-[#1dd1c1] px-3 py-1 text-xs font-black text-[#071c36]">ขั้นที่ 2</span><h3 className="mt-4 text-lg font-black">แปลงจากฐาน 10 เป็นฐาน {to}</h3>{to===10?<p className="mt-3 leading-7 text-slate-300">โจทย์ต้องการฐาน 10 จึงตอบ <b className="text-[#ffcf5c]">{value}<sub>10</sub></b> ได้ทันที</p>:<><p className="mt-3 text-sm text-slate-300">นำ {value}<sub>10</sub> หารด้วย {to} ซ้ำจนผลหารเป็น 0</p><div className="mono mt-3 space-y-1 text-sm">{divisions.map((x,i)=><p key={i} className="rounded bg-white/10 px-3 py-2">{x}</p>)}</div><p className="mt-3 rounded bg-white/10 p-3 text-[#ffcf5c]">อ่านเศษจาก <b>ล่างขึ้นบน</b> ได้ <b>{result}<sub>{to}</sub></b></p></>}</section></div>
      <div className="mt-5 rounded-xl border-l-4 border-[#ffb524] bg-[#fff6df] p-4"><b>สรุปเส้นทาง:</b> ฐาน {from} → ฐาน 10 → ฐาน {to}<p className="mt-1 text-sm text-slate-600">คำตอบคือ <b>{shown}<sub>{from}</sub> = {result}<sub>{to}</sub></b></p></div>
    </article>
    <section className="mt-8"><h2 className="text-xl font-black">เลือกบทเรียนครบทั้ง 20 คู่ฐาน</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 md:grid-cols-4">{BASES.flatMap(a=>BASES.filter(b=>b!==a).map(b=><button key={`${a}-${b}`} onClick={()=>chooseRoute(a,b)} className={`rounded-lg border px-3 py-3 text-sm font-bold ${from===a&&to===b?"border-[#1dd1c1] bg-[#1dd1c1]":"bg-white hover:border-[#1dd1c1]"}`}>ฐาน {a} → ฐาน {b}</button>))}</div></section>
    <button onClick={()=>go("practice")} className="mt-8 rounded-lg bg-[#1dd1c1] px-6 py-3 font-bold">เข้าใจแล้ว ไปโจทย์ฝึก →</button>
  </main></>
}
function BasePicker({label,value,set,disabled}:{label:string,value:number,set:(b:number)=>void,disabled?:number}){return <div className="mb-4 grid items-center gap-3 md:grid-cols-[130px_1fr]"><b>{label}</b><div className="flex gap-2">{BASES.map(b=><button disabled={b===disabled} onClick={()=>set(b)} key={b} className={`h-11 w-12 rounded-lg border font-bold disabled:opacity-20 ${value===b?"bg-[#1dd1c1]":"bg-white"}`}>{b}</button>)}</div></div>}
function Levels({level,set}:{level:Level,set:(l:Level)=>void}){return <div className="grid gap-3 md:grid-cols-3">{(["easy","medium","hard"] as Level[]).map((l,i)=><button key={l} onClick={()=>set(l)} className={`choice rounded-xl p-5 text-left text-white ${level===l?"active":""} ${i===0?"bg-green-600":i===1?"bg-amber-500":"bg-red-500"}`}><b className="text-xl">{"★".repeat(i+1)} {NAMES[l]}</b><small className="mt-2 block">สูงสุด {i===0?31:i===1?255:"4,095"}</small></button>)}</div>}
function Practice({go}:{go:(t:Tab)=>void}){const[level,setLevel]=useState<Level>("easy"),[q,setQ]=useState(()=>makeQ("easy")),[input,setInput]=useState(""),[done,setDone]=useState(false),[score,setScore]=useState([0,0]);const change=(l:Level)=>{setLevel(l);setQ(makeQ(l));setInput("");setDone(false)};const check=()=>{if(!input||done)return;setDone(true);setScore(([c,t])=>[c+(input.toUpperCase()===q.answer?1:0),t+1])};return <><Hero tag="GUIDED PRACTICE" title="โจทย์ฝึกพร้อมเฉลย" sub="เลือกความยาก ตอบทีละข้อ แล้วดูวิธีคิดทันที"/><main className="glass mx-auto -mt-8 mb-20 max-w-5xl rounded-xl bg-white p-6 md:p-10"><Levels level={level} set={change}/><section className="mt-6 rounded-xl bg-emerald-50 p-6"><span className="float-right font-bold">ฝึกถูก {score[0]}/{score[1]}</span><p className="text-sm text-[#008f86]">ระดับ{NAMES[level]}</p><h2 className="my-4 text-2xl font-black">แปลง {q.shown}<sub>{q.from}</sub> เป็นฐาน {q.to}</h2><div className="flex flex-wrap gap-2"><input value={input} onChange={e=>setInput(e.target.value)} className="h-12 flex-1 rounded-lg border px-4" placeholder="คำตอบ"/><button onClick={check} className="rounded-lg bg-[#1dd1c1] px-6 font-bold">ตรวจ</button><button onClick={()=>{setQ(makeQ(level));setInput("");setDone(false)}} className="rounded-lg border bg-white px-6">ข้อใหม่</button></div>{done&&<div className={`mt-4 rounded-lg p-4 ${input.toUpperCase()===q.answer?"bg-green-100":"bg-red-100"}`}><b>{input.toUpperCase()===q.answer?"✓ ถูกต้อง":"✕ ยังไม่ถูก"}</b><p>เฉลย: {q.shown}<sub>{q.from}</sub> = {q.answer}<sub>{q.to}</sub></p><p className="text-sm text-slate-600">แปลงเป็นฐาน 10 ได้ {q.decimal} แล้วหารซ้ำด้วย {q.to}</p></div>}</section><button onClick={()=>go("exam")} className="mt-6 rounded-lg bg-[#071c36] px-6 py-3 text-white">พร้อมแล้ว ไปโจทย์จริง →</button></main></>}
function Exam({go,save}:{go:(t:Tab)=>void,save:(r:Record)=>void}){const[level,setLevel]=useState<Level>("easy"),[qs,setQs]=useState<Q[]>([]),[answers,setAnswers]=useState<string[]>([]),[result,setResult]=useState<number|null>(null);const start=()=>{setQs(Array.from({length:10},()=>makeQ(level)));setAnswers(Array(10).fill(""));setResult(null)};const submit=()=>{if(answers.some(x=>!x))return alert("กรุณาตอบให้ครบ 10 ข้อ");const correct=qs.filter((q,i)=>q.answer===answers[i].toUpperCase()).length;setResult(correct);save({date:new Date().toISOString(),level,correct,total:10})};return <><Hero tag="RANDOM EXAM" title="โจทย์จริงแบบสุ่ม" sub="10 ข้อ คนละชุดทุกครั้ง ตรวจและเฉลยหลังส่งครบ"/><main className="glass mx-auto -mt-8 mb-20 max-w-5xl rounded-xl bg-white p-6 md:p-10">{!qs.length?<><Levels level={level} set={setLevel}/><button onClick={start} className="mt-6 w-full rounded-lg bg-[#071c36] py-4 font-bold text-white">เริ่มข้อสอบระดับ{NAMES[level]}</button></>:result===null?<><div className="grid gap-3 md:grid-cols-2">{qs.map((q,i)=><label key={i} className="rounded-lg bg-slate-100 p-4"><b>ข้อ {i+1}: </b>แปลง {q.shown}<sub>{q.from}</sub> เป็นฐาน {q.to}<input value={answers[i]} onChange={e=>setAnswers(a=>a.map((x,j)=>j===i?e.target.value:x))} className="mt-2 block h-10 w-full rounded border bg-white px-3"/></label>)}</div><button onClick={submit} className="mt-6 w-full rounded-lg bg-[#1dd1c1] py-4 font-bold">ส่งคำตอบและดูเฉลย</button></>:<><h2 className="text-center text-3xl font-black">ได้ {result}/10 คะแนน</h2><div className="mt-6 grid gap-3 md:grid-cols-2">{qs.map((q,i)=>{const ok=q.answer===answers[i].toUpperCase();return <div key={i} className={`rounded-lg border-l-4 p-4 ${ok?"border-green-500 bg-green-50":"border-red-500 bg-red-50"}`}><b>{ok?"✓ ถูก":"✕ ผิด"} ข้อ {i+1}</b><p>ตอบ {answers[i]} • เฉลย {q.answer}<sub>{q.to}</sub></p><small>มีค่า {q.decimal} ในฐาน 10</small></div>})}</div><div className="mt-6 flex gap-2"><button onClick={()=>setQs([])} className="rounded-lg border px-5 py-3">ทำชุดใหม่</button><button onClick={()=>go("score")} className="rounded-lg bg-[#071c36] px-5 py-3 text-white">ดูคะแนน →</button></div></>}</main></>}
function Calculator(){const[from,setFrom]=useState(2),[to,setTo]=useState(10),[input,setInput]=useState("10110"),[result,setResult]=useState("22");const calc=()=>{try{let n=0n;for(const c of input.toUpperCase()){const d=parseInt(c,36);if(Number.isNaN(d)||d>=from)throw 0;n=n*BigInt(from)+BigInt(d)}setResult(n.toString(to).toUpperCase())}catch{setResult("ค่าที่กรอกไม่ถูกต้อง")}};return <><Hero tag="AUTO CONVERTER" title="เครื่องคำนวณเลขฐาน" sub="เฉพาะฐาน 2, 6, 8, 10 และ 16"/><main className="glass mx-auto -mt-8 mb-20 grid max-w-4xl gap-6 rounded-xl bg-white p-6 md:grid-cols-2 md:p-10"><div><label className="font-bold">ค่าที่ต้องการแปลง</label><input value={input} onChange={e=>setInput(e.target.value)} className="mono mt-2 h-16 w-full rounded-lg border bg-slate-50 px-4 text-2xl"/><div className="mt-4 grid grid-cols-2 gap-3"><select value={from} onChange={e=>setFrom(+e.target.value)} className="h-12 rounded border px-3">{BASES.map(b=><option key={b}> {b}</option>)}</select><select value={to} onChange={e=>setTo(+e.target.value)} className="h-12 rounded border px-3">{BASES.map(b=><option key={b}> {b}</option>)}</select></div><button onClick={calc} className="mt-4 w-full rounded-lg bg-[#1dd1c1] py-3 font-bold">แปลงค่า</button></div><div className="rounded-xl bg-[#071c36] p-6 text-white"><p className="text-[#1dd1c1]">ผลลัพธ์</p><output className="mono mt-5 block break-all text-4xl font-bold">{result}</output><p className="mt-4 text-slate-400">{input}<sub>{from}</sub> → ฐาน {to}</p></div></main></>}
function Score({records,remove,clear,go}:{records:Record[],remove:(i:number)=>void,clear:()=>void,go:(t:Tab)=>void}){const correct=records.reduce((s,x)=>s+x.correct,0),total=records.reduce((s,x)=>s+x.total,0),pct=total?Math.round(correct/total*100):0;return <><Hero tag="EXAM SCORE" title="คะแนนโจทย์จริง" sub="คะแนนล่าสุด ความแม่นยำ และประวัติการสอบ"/><main className="glass mx-auto -mt-8 mb-20 max-w-4xl rounded-xl bg-white p-6 md:p-10"><div className="grid items-center gap-8 md:grid-cols-[180px_1fr]"><div style={{"--score":`${pct*3.6}deg`} as React.CSSProperties} className="score-ring grid h-44 w-44 place-items-center rounded-full border-[14px] border-white text-3xl font-black">{pct}%</div><div><p className="text-[#008f86]">คะแนนล่าสุด</p><h2 className="text-3xl font-black">{records.length?`${records[0].name||"ไม่ระบุชื่อ"}: ${records[0].correct}/10 คะแนน`:"ยังไม่มีคะแนน"}</h2><button onClick={()=>go("exam")} className="mt-4 rounded-lg bg-[#1dd1c1] px-5 py-3">ทำโจทย์จริง</button></div></div><div className="mt-8">{records.map((r,i)=><div key={i} className="grid grid-cols-[1.4fr_1fr_70px_55px] items-center gap-2 border-b py-3"><span>{r.name||"ไม่ระบุชื่อ"}</span><span>ระดับ{NAMES[r.level]}</span><b className="text-right">{r.correct}/{r.total}</b><button onClick={()=>remove(i)} className="rounded border border-red-300 px-2 py-1 text-sm text-red-600">ลบ</button></div>)}</div>{records.length>0&&<button onClick={clear} className="mt-6 text-sm text-red-600 underline">ล้างคะแนนทั้งหมด</button>}</main></>}
